
GET  http://localhost:3000/mentors 


### 2. Create a New Booking (POST /bookings)

###  student 1 
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "student_id": 101,
  "mentor_id": 1,
  "area_of_interest": "Digital Marketing",
  "duration": 45,
  "scheduled_time": "2024-08-22T19:00:00Z"
}
### student 2

POST http://localhost:3000/bookings
Content-Type: application/json

{
  "student_id": 102,
  "mentor_id": 3,
  "area_of_interest": "Data Science",
  "duration": 90,
  "scheduled_time": "2024-08-23T15:00:00Z"
}
### student 3

POST http://localhost:3000/bookings
Content-Type: application/json

{
  "student_id": 103,
  "mentor_id": 2,
  "area_of_interest": "Web Development",
  "duration": 60,
  "scheduled_time": "2024-08-24T10:30:00Z"
}

### student 4
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "student_id": 105,
  "mentor_id": 4,
  "area_of_interest": "Project Management",
  "duration": 120,
  "scheduled_time": "2024-08-26T14:00:00Z"
}
### student 5
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "student_id": 106,
  "mentor_id": 5,
  "area_of_interest": "UI/UX Design",
  "duration": 75,
  "scheduled_time": "2024-08-27T11:30:00Z"
}

###
GET http://localhost:3000/bookings?student_id=101
###
GET http://localhost:3000/bookings?student_id=102
### 
GET http://localhost:3000/bookings?student_id=103
###
GET http://localhost:3000/bookings?student_id=104